language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-nrpe.gemspec
- gem install sensu-plugins-nrpe-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: NEgcwZMWFsYy2GN8b/DMdm+Ld9QOtBABpndfRWMv2EddzmqiYpc92Ct/vocUB7cuvfn/ICA2MQCUSVYKeywb9QdtXMhZ93cF67R4CrBIVkCeAvtrSevb3u4e9Ofkr57yCEYZ4WcTNt2xKCShmPAWGGv0zcjCol8vpJT2RGfaxMCXx+ViVTr6JuQeI5ZbXGopBgXmfY7j8CHJjbKBG55w5SRssLOKrxqsw29dK3H2eCHDjXUhVAUB9Bkg3P34enF/eN9BxQz1bPKzNgaeYZqX1gODw5M+HyZS+ogJxGVKCM0n6pPuhAe3p948XHqrwS6RV/MTSYCXrI7uOAutH2CdhiWy7UGuwlv7yrAmWooDmtAYQdMjAFy5tYp0xehqtnI4NNC1MyQ6XoXLFYRatp+llYC99LWB9DkhBgEdzVjGqjCqPbaY5fTVNAvQq6fXWDYU7U/Fb2o7OZK9wdWoqWnLBrdSI0WZberWCC4sC0+6Nd6Y326I8U0OQ8G43a5rH3czas7H9Hbh1W7604dCcJEpTV9pZ0eaCH3K2EKgEIUdZtu/DvMYt30AVj3ckkC0VkjTDReMTAn8jQ48ThtMZZSYX05ztwjfC4ayQ1b0xbhtPyOxZfLlCKRTLsJt18OL2291vQaZggssLjD0pQms5NrLJSyN7mXyj+eWxQlL2Noh4Xs=
  gem: sensu-plugins-nrpe
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-nrpe
